''' This module has a function that changes the privileges of all files and folders in the common directory of the pipeline, especially the ones that were generated by 
    antiSMASH and BiGSCAPE, so that all non-root users can modify and move these files and folders. '''


import os


def change_permit_of_all_folders_and_files_in_common_dir(): # Note: this function does not have input or output.
    path_of_common_dir = os.path.dirname(os.path.realpath(__file__))

    for dir, subdirs, files in os.walk(path_of_common_dir):
        for subdir in subdirs:
            os.system("chmod 777 " + os.path.join(dir, subdir)) # "777" means to grant all users and groups rights to read, write and execute.
        for file in files:
            os.system("chmod 777 " + os.path.join(dir, file))
