#!/bin/bash

# This is a Bash script for making a short running command of the pipeline. The command for running the pipeline is:
# ./run_pipeline 
# and should be executed in Terminal opened in common directory (i.e. directory that contains all files and folders of the pipeline).

sudo python start_and_command.py 

# Note: user password is required due to usage of sudo. The running command uses sudo due to docker commands in scripts of antiSMASH and BiGSCAPE. By default, docker can only be run by root (i.e. with sudo). Hence, without sudo, the two programs cannot be executed.
